### ISSUE TITLE
No books?

### ISSUE THREAD

**Issue by pjlamine** [datdarylngo/Books#1]
There’s no books in here, Dat. What gives.

**Comment by arizedatngo** [comment]
@pjlamine they are set on private for copy-write issues. Let me make this whole repo private haha
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/97070834/164934793-d3f5e5d4-1e60-4542-a4c0-268b56e74c47.png">

**Comment by arizedatngo** [comment]
@pjlamine Was this picture taken 10 years ago?

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/97070834/164936972-83e9e409-37d0-4356-a14f-ebc92b314c08.png">

**Comment by pjlamine** [comment]
Summer 2015 😬
